Django/urls.py
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('account.urls', namespace='account')),  # account
    url('', include('PalePink.urls', namespace='PalePink')),  # PalePink
    url('', include('photo.urls', namespace='photo')),  # photo
    url('', include('article.urls', namespace='program')),  # article
    url('captcha', include('captcha.urls'))
]

PalePink/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'home/$', views.home, name='home'),
    url(r'mall/$', views.Mall.as_view(), name='mall'),
]
app_name = 'PalePink'

account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'login/$', views.login, name='login'),
    url(r'logout/$', views.logout, name='logout'),
    url(r'register/$', views.register, name='register'),
    url(r'background/$', views.background, name='background')
]
app_name = 'account'

article/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'Article/$', views.articles, name='article'),
    url(r'article-column/$', views.article_column, name='article_column'),
    url(r'column-rename/$', views.rename_article_column, name='column_rename'),
    url(r'del-column/$', views.del_article_column, name='del_column'),
    url(r'article-post/$', views.article_post, name='article_post'),
    url(r'article-list/$', views.article_list, name='article_list'),
    url(r'article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_details'),
    url(r'del-article/$', views.del_article, name='del_article'),
    url(r'edit-article/(?P<article_id>\d+)/$', views.edit_article, name='edit_article'),
    url(r'article-tag/$', views.article_tag, name='article_tag'),
    url(r'edit_tag/$', views.edit_tag, name='edit_tag'),
    url(r'del_tag/$', views.del_tag, name='del_tag'),
    url(r'detail/(?P<id>\d+)/(?P<slug>[-\w]+)$', views.detail, name='detail')
]
app_name = 'article'

photo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'Image/$', views.image, name='Image'),
]
app_name = 'photo'

templates/common/background.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script rel="stylesheet" src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script rel="stylesheet" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script rel="stylesheet" src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'fonts/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
{% include 'common/header.html' %}
{% block content %}
    <div class="container font-apple">
    <div class="row" style="margin-top: 20px">
        <div class="col-md-2 list-group " id="list" >
            <a class="list2" style="margin-top: 20px">文章管理</a>
            <div class="list1 list-group" style="padding: 20px; font-size: 111px">
                <a href="{% url 'article:article_column'%}">栏目管理</a>
                <a href="{% url 'article:article_post' %}">发布文章</a>
                <a href="{% url 'article:article_list' %}">文章列表</a>
                <a href="{% url 'article:article_tag' %}">文章标签</a>
            </div>
            <a class="list2" style="margin-top: 20px">图片管理</a>
            <div class="list1 list-group" style="padding: 20px">
                <a>发布图片</a>
                <a>图片风格</a>
            </div>
            <a class="list2" style="margin-top: 20px">视频管理</a>
            <div class="list1 list-group" style="padding: 20px">
                <a>发布视频</a>
                <a>视频类型</a>
            </div>
            <a class="list2" style="margin-top: 20px">关于本站</a>
            <div class="list1 list-group" style="padding: 20px">
                <a>帮助中心</a>
                <a>客服中心</a>
            </div>
        </div>
        <div class="col-md-10">
            {% block body %}{% endblock %}
        </div>
    </div>
    </div>
    <link href="{% static 'css/home.css' %}">
{% endblock %}
{% include 'common/footer.html' %}
</body>
</html>

templates/common/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="text-center">
    <a style="font-weight: bold; font-size: 13px; color: dimgrey">Copyright &copy2018 PalePink </a>
</div>
</body>
</html>

templates/common/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
{% load staticfiles %}
<div id="myNav" class="nav-fill container-fluid font-apple">
<!--导航栏-->
<nav id="myNav" class="navbar nav-fill fixed-top">
<ul class="nav">
    <li class="nav-item myNav1">
      <a class="nav-link" href="{% url 'PalePink:home' %}">首页</a>
    </li>
    <li class="nav-item myNav1">
      <a class="nav-link" href="{% url 'photo:Image' %}">摄影</a>
    </li>
    <li class="nav-item myNav1">
      <a class="nav-link" href="{% url 'article:article' %}">文章</a>
    </li>
    <li class="nav-item myNav1">
      <a class="nav-link" href="{% url 'PalePink:mall' %}">商城</a>
    </li>
  </ul>
    <ul class="nav justify-content-end">
    <li class="nav-item myNav1">
        <label for="1"></label>
        <input style="width: 150px; height: 30px;margin-top: 3px" id="1"> <!-- 搜索框 -->
    </li>
    <li class="nav-item myNav1">
      <a class="nav-link" href="{% url 'article:article_post' %}">创作</a>
    </li>
    {% if user.is_authenticated %}
        <li class="nav-item myNav1" style="margin-left: -10px">
            <a class="nav-link" href="{% url 'account:background' %}">{{ user.username }}</a>
        </li>
        <li class="nav-item myNav1">
            <a class="nav-link" href="{% url 'account:logout' %}">退出</a>
        </li>
    {% else %}
    <li class="nav-item myNav1">
      <a class="nav-link" onclick="showLogin()">登录</a>
    </li>
    <li class="nav-item myNav2">
      <a class="nav-link">or</a>
    </li>
    <li class="nav-item myNav1">
      <a class="nav-link" href="{% url 'account:register' %}">注册</a>
    </li>
    {% endif %}
  </ul>
</nav>
<!--登录-->
<div id="hidden" style="margin-top: 100px;">
    <form action="{% url 'account:login' %}" method="post">
        {% csrf_token %}
        <div class="login-item">
            <label for="username" style="font-size: 25px"><span class="fa fa-user"></span></label>
            <input id="username" type="text" name="username" value="{{ username }}" placeholder="username">
        </div>
        <div class="login-item">
            <label for="password" style="font-size: 25px"><span class="fa fa-lock"></span></label>
            <input id="password" type="password" name="password" value="{{ password }}" placeholder="password">
        </div>
        <div class="text-center" style="margin-top: 20px">
            <input class="login" type="submit"  value="登录">
        </div>

    </form>
</div>
</div>
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'layui/layer.js' %}"></script>
    <script src="{% static 'js/home.js' %}"></script>
</body>
</html>

templates/common/home.html
{% extends 'common/index.html' %}
{% block title %}首页{% endblock %}
{% block content %}
    <div class="container">
    <a>占位</a>
    </div>
{% endblock %}

templates/common/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script rel="stylesheet" src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script rel="stylesheet" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script rel="stylesheet" src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'fonts/css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<body>
<div class="font-apple">
{% include 'common/header.html' %}
{% block content %}{% endblock %}
{% include 'common/footer.html' %}
</div>
</body>
</html>

templates/common/paginator.html
<div class="pagination mTitle row" style="font-size: 14px; margin-top: 15px">
    <span class="step-links">
        {% if page.has_previous %}
        <a style="color: black;margin-right: 10px"href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <a class="current">
            第 {{ page.number }}页<span style="margin-left: 2em">共{{ page.paginator.num_pages }}页</span>
        </a>
        {% if page.has_next %}
        <a style="color: black;margin-left: 10px" href="?page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>