Django/urls.py
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('account.urls', namespace='account')),  # account
    url('', include('PalePink.urls', namespace='PalePink')),  # PalePink
    url('', include('photo.urls', namespace='photo')),  # photo
    url('', include('article.urls', namespace='program')),  # article
    url('captcha', include('captcha.urls'))
]

article/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'Article/$', views.articles, name='article'),
    url(r'article-column/$', views.article_column, name='article_column'),
    url(r'column-rename/$', views.rename_article_column, name='column_rename'),
    url(r'del-column/$', views.del_article_column, name='del_column'),
    url(r'article-post/$', views.article_post, name='article_post'),
    url(r'article-list/$', views.article_list, name='article_list'),
    url(r'article-detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.article_detail, name='article_details'),
    url(r'del-article/$', views.del_article, name='del_article'),
    url(r'edit-article/(?P<article_id>\d+)/$', views.edit_article, name='edit_article'),
    url(r'article-tag/$', views.article_tag, name='article_tag'),
    url(r'edit_tag/$', views.edit_tag, name='edit_tag'),
    url(r'del_tag/$', views.del_tag, name='del_tag'),
    url(r'detail/(?P<id>\d+)/(?P<slug>[-\w]+)$', views.detail, name='detail')
]
app_name = 'article'

photo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'Image/$', views.image, name='Image'),
]
app_name = 'photo'

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from slugify import slugify


class ArticleColumn(models.Model):
    user = models.ForeignKey(User, related_name='article_column', on_delete=models.CASCADE)
    column = models.CharField(max_length=200)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.column


class ArticleTag(models.Model):
    author = models.ForeignKey(User, related_name='tag', on_delete=models.CASCADE)
    tag = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.tag


class ArticlePost(models.Model):
    author = models.ForeignKey(User, related_name='article', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=500)
    column = models.ForeignKey(ArticleColumn, related_name='article_column', on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    article_tag = models.ManyToManyField(ArticleTag, related_name='article_tag', blank=True)

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(ArticlePost, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:article_details', args=[self.id, self.slug])

    def get_url(self):
        return reverse('article:detail', args=[self.id, self.slug])

article/forms.py
from django import forms
from . import models


class ArticleColumnForm(forms.ModelForm):
    class Meta:
        model = models.ArticleColumn
        fields = ('column',)


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = models.ArticlePost
        fields = ('title', 'body')


class ArticleTagForm(forms.ModelForm):
    class Meta:
        model = models.ArticleTag
        fields = ('tag',)

templates/article/article_column.html
{% extends 'common/background.html' %}
{% load staticfiles %}
{% block title %}文章{% endblock %}
{% block body %}
<div style="margin-top: 20px">
    <p class="text-right"><button id="add_column" onclick="add_column()"  class="btn btn-primary">添加栏目</button></p>
    <table class="table table-hover text-center">
        <tr>
            <td>序号</td>
            <td>栏目名称</td>
            <td>创建时间</td>
            <td>更新时间</td>
            <td>操作</td>
        </tr>
        {% for column in columns %}
        <tr>
            <td width="10%">{{ forloop.counter }}</td>
            <td width="20%">{{ column.column }}</td>
            <td width="20%">{{ column.created |date:"F d,y"}}</td>
            <td width="20%">{{ column.updated |date:"F d,y"}}</td>
            <td width="10%">
                <a name="edit" href="javascript:" onclick="edit_column(this,{{ column.id }})" style="color: black">
                    <span class="fa fa-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="del_column(this,{{ column.id }})" style="color: black">
                    <span class="fa fa-trash-o" style="margin-left: 20px"></span>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
    <div class="text-center" id="hidden1">{{ column_form.column }}</div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'layui/layer.js' %}"></script>
    <script>
    function add_column() {
        layer.open({
            type:1,
            skin:'layui-layer-demo',
            title:'新增栏目',
            area:['300px','210px'],
            content:$('#hidden1'),
            btn:['确定','取消'],
            yes:function () {
                column_name = $('#id_column').val();
                $.ajax({
                    url:'{% url "article:article_column" %}',
                    type:'POST',
                    data:{"column":column_name},
                    success:function (e) {
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg('Ok');
                        }else {
                            layer.msg('error')
                        }
                    },
                });
            },
            btn2:function (index, layero) {
                layer.close(index);
            }
        });
    }

function edit_column(the,column_id) {
        var name=$(the).parents("tr").children("td").eq(1).text();
        var index=layer.open({
            type:1,
            area:['400px','200px'],
            title:"编辑栏目",
            content:'<div class="text-center" style="margin-top:2px"><p>请编辑栏目的名称</p>' +
            '<p><input type="text" id="new_name" value="'+name+'"></p></div>',
            btn:['确定','取消'],
            yes:function (index,layro) {
                new_name = $("#new_name").val();
                $.ajax({
                    url:"{% url 'article:column_rename' %}",
                    type:"POST",
                    data:{"column_id":column_id,"column_name":new_name},
                    time:4000,
                    success:function (e) {
                        if (e=='1') {
                            parent.location.reload();
                            layer.msg("修改成功");
                        } else {
                            layer.msg("修改失败");
                        }
                    },
                });
            },
        });
    }
    function del_column(the, column_id) {
        var name =$(the).parents('tr').children('td').eq(1).text();
        layer.open({
            type:1,
            area:['400px','200px'],
            title:'删除栏目',
            content:'<div class="text-center" style="margin-top:30px"><p>是否确定删除 '+name+' 栏目</p></div>',
            btn:['确定','取消'],
            yes:function () {
                $.ajax({
                    url:'{% url "article:del_column" %}',
                    type:"POST",
                    data:{'column_id':column_id},
                    success:function (e) {
                        if(e=='1') {
                        parent.location.reload();
                        layer.msg('删除成功');
                        }else{
                            layer.msg('删除失败');
                        }
                    },
                })
            },
        });
    }
    </script>
{% endblock %}

templates/article/article_detail.html
{% extends 'common/background.html' %}
{% load staticfiles %}
{% block title %}article list{% endblock %}
{% block body %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" >
    <div style="margin-top: 30px;margin-left: 0px">
        <a style="font-size: 20px">{{ article.title }}</a>
        <a class="text-right author" href="#">作者: {{ user.username }}</a>
    </div>
    {% if article.article_tag.all %}
    <span class="fa fa-tags" style=" font-size: 12px"><a style="margin-left: 5px;">{{ article.article_tag.all | join:"," }}</a></span>
    {% else %}
    {% endif %}
    <div id="editormd-view" style="margin-top: 20px">
        <textarea id="append-test" style="display: none" >{{ article.body }}</textarea>
    </div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js'%}"></script>
    <script type="text/javascript">
    $(function () {
        editormd.markdownToHTML('editormd-view',{
            htmlDecode      : "style,script,iframe",  // you can filter tags decode
        emoji           : true,
        taskList        : true,
        tex             : true,  // 默认不解析
        flowChart       : true,  // 默认不解析
        sequenceDiagram : true,  // 默认不解析
        });
    });
    </script>
{% endblock %}

templates/article/article_detail_user.html
{% extends 'common/index.html' %}
{% load staticfiles %}
{% block title %}文章{% endblock %}
{% block content %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}" >
    <div class="container list-group">
    <div style="margin-top: 30px">
        <h3 class="mTitle">{{ article.title }}</h3>
    </div>
    <div class="mTitle author">
    <a>{{ article.author.username }}：</a>
    {% if article.article_tag.all %}
        <span class="fa fa-tag" style=" font-size: 12px"><a style="margin-left: 5px;">{{ article.article_tag.all | join:"," }}</a></span>
    {% else %}
    {% endif %}
    </div>
    <div id="editormd-view" style="margin-top: 10px" class="row">
        <textarea id="append-test" style="display: none" >{{ article.body }}</textarea>
    </div>
    </div>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'editor/lib/marked.min.js' %}"></script>
    <script src="{% static 'editor/lib/prettify.min.js' %}"></script>
    <script src="{% static 'editor/lib/raphael.min.js' %}"></script>
    <script src="{% static 'editor/lib/underscore.min.js' %}"></script>
    <script src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
    <script src="{% static 'editor/lib/flowchart.min.js' %}"></script>
    <script src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js'%}"></script>
    <script type="text/javascript">
    $(function () {
        editormd.markdownToHTML('editormd-view',{
            htmlDecode      : "style,script,iframe",  // you can filter tags decode
        emoji           : true,
        taskList        : true,
        tex             : true,  // 默认不解析
        flowChart       : true,  // 默认不解析
        sequenceDiagram : true,  // 默认不解析
        });
    });
    </script>
{% endblock %}

templates/article/article_list.html
{% extends 'common/background.html' %}
{% load staticfiles %}
{% block title %}article list{% endblock %}
{% block body %}
    <div style="margin-top: 20px">
    <table class="table table-hover text-center " style="table-layout:fixed">
        <tr>
            <td width="10%">序号</td>
            <td width="25%">标题</td>
            <td width="15%">栏目</td>
            <td width="20%">创建时间</td>
            <td width="20%">最后修改时间</td>
            <td width="10%">操作</td>
        </tr>
        {% for article in articles %}
        <tr id="{{ forloop.id }}">
            <td>{{ forloop.counter }}</td>
            <td class="text-left" id="myTable"><a href="{{ article.get_absolute_url }}" style="color: black">{{ article.title }}</a></td>
            <td>{{ article.column }}</td>
            <td>{{ article.created |date:"F d,y H:i:s" }}</td>
            <td>{{ article.updated |date:"F d,y H:i:s" }}</td>
            <td>
                <a name="edit" href="{% url 'article:edit_article' article.id %}" style="color: black">
                    <span class="fa fa-pencil"></span>
                </a>
                <a name="delete" href="javascript:" onclick="del_article(this,{{ article.id }})" style="color: black">
                    <span class="fa fa-trash-o" style="margin-left: 20px"></span>
                </a>
                </a>
            </td>
        </tr>
        {% endfor %}
    </table>
        <div class="col-md-2 text-right">{% include 'common/paginator.html' %}</div>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'layui/layer.js'%}"></script>
    <script type="text/javascript">
    function del_article(the, article_id) {
        var name =$(the).parents('tr').children('td').eq(1).text();
        layer.open({
            type:1,
            area:['400px','200px'],
            title:'删除栏目',
            content:'<div class="text-center" style="margin-top:30px"><p>是否确定删除 '+name+' 栏目</p></div>',
            btn:['确定','取消'],
            yes:function () {
                $.ajax({
                    url:'{% url "article:del_article" %}',
                    type:"POST",
                    data:{'article_id':article_id},
                    success:function (e) {
                        if(e=='1') {
                        parent.location.reload();
                        layer.msg('has been deleted.');
                        }else{
                            layer.msg('删除失败');
                        }
                    },
                })
            },
        });
    }
    </script>

{% endblock %}

templates/article/article_post.html
{% extends 'common/background.html' %}
{% load staticfiles %}
{% block title %}article post{% endblock %}
{% block body %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
    <div class="position-fixed col-md-7">
    <form class="form-horizontal" action="." method="post">{% csrf_token %}
        <div class="row" style="margin-top: 30px">
            <a>标题：{{ article_post_form.title }}</a>
        </div>
        <div class="row" style="margin-top: 10px;">
            <a>栏目:
            <select id="which_column" style="margin-left: 8px">
                {% for column in article_columns %}
                    <option value="{{ column.id }}">{{ column.column }}</option>
                {% endfor %}
            </select>
            </a>
            <div>
                {% for tag in article_tags %}
                <label class="checkbox-inline" style="margin-left: 10px">
                    <input class="tagcheckbox " type="checkbox" id="{{ tag.id }}" name="article_tag" value="{{ tag.tag }}">{{ tag.tag }}
                </label>
                {% endfor %}
            </div>
        </div>
        <div class="row" style="margin-top: 10px">
            <div id="editormd" class="editormd" >
                <textarea style="display: none;" id="id_body">write something?</textarea>
            </div>
        <div class="offset-11">
            <input type="button" class="button" value="发布" onclick="publish_article()">
        </div>
        </div>
    </form>
    </div>
    <script type="text/javascript" src="{% static 'editor/examples/js/jquery.min.js' %}"></script>
    <script src="{% static 'editor/editormd.js' %}"></script>
    <script src="{% static 'js/json2.js' %}"></script>
    <script type="text/javascript">
    function publish_article() {
        var title = $("#id_title").val();
        var column_id = $("#which_column").val();
        var body = $("#id_body").val();
        var article_tags = [];
        $.each($("input[name='article_tag']:checked"),
        function () {
            article_tags.push($(this).val());
        });
        $.ajax({
            url:"{% url 'article:article_post' %}",
            type:'POST',
            data:{'title':title,'body':body,'column_id':column_id,'tags':JSON.stringify(article_tags)},
            success:function (e) {
                if(e=='1'){
                    layer.msg('successful');
                    location.href="{% url 'article:article_list' %}"
                }else if(e=='2'){
                    layer.msg('sorry');
                }else {
                    layer.msg('项目名称必须填，不能为空');
                }
            },
        })
    }
    $(function () {
        editormd('editormd',{
            width:'100%',
            height:500,
            syncScrolling:'single',
            path:"{% static 'editor/lib/' %}",
            emoji:true,
        });
    });
    </script>
{% endblock %}

templates/article/articles.html
{% extends 'common/index.html' %}
{% block title %}文章{% endblock %}
{% block content %}
    <div class="container">
        <h3 class="text-center font-weight-bold" style="margin-top: 30px">往事如风，莫失莫忘</h3>
    <div style="margin-top: 25px;">
    {% for article in articles %}
        <div class="list-group row" style="margin-top: 20px">
            <a class="mTitle" href="{{ article.get_url }}">{{ article.title }}</a>
            <a style="color:grey" class="content1">{{ article.body|safe |cut:'&emsp;'}}</a>
            <a class="mTitle author" href="{% url 'article:article'%}">  作者: {{ article.author.username }}</a>
        </div>
        <hr>
    {% endfor %}
    {% include 'common/paginator.html' %}
    </div>
    </div>
{% endblock %}

templates/article/edit_article.html
{% extends 'common/background.html' %}
{% block title %}article column{% endblock %}
{% load staticfiles %}
{% block body %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
    <div class="position-fixed col-md-7" style="margin-left:10px">
        <form class="form-horizontal" action="." method="post">{% csrf_token %}
            <div class="row" style="margin-top: 30px">
                <span>标题：</span>
                <div class="text-left">{{ this_article_form.title }}</div>
            </div>
            <div class="row" style="margin-top: 10px">
                <span>栏目：</span>
                <select id="which_column">
                    {% for column in article_columns %}
                        {% if column == this_article_column.column %}
                            <option value="{{ column.id }}" selected="selected">{{ column.column }}</option>
                        {% else %}
                            <option value="{{ column.id }}">{{ column.column }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="row" style="margin-top: 10px">
                <div id="editormd">
                    <textarea style="display: none" id="id_body">{{ article.body }}</textarea>
                </div>
                <div class="offset-11">
                    <input type="button" class="button" value="发布" onclick="publish_article()">
                </div>
            </div>
        </form>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'layui/layer.js' %}"></script>
    <script type="text/javascript">
    $(function redit_article() {
        var editor = editormd('editormd',{
            width:'100%',
            height:'500',
            //syncScrolling:'single',
            path:"{% static 'editor/lib/' %}",
        });
    });
    function publish_article() {
     var title=$("#id_title").val();
     var column_id=$("#which_column").val();
     var body=$("#id_body").val();
     $.ajax({
         url:"{% url 'article:edit_article' article.id %}",
         type:'POST',
         data:{"title":title, "body":body, "column_id":column_id},
         success:function (e) {
             if(e=='1'){
                 layer.msg('successful');
                 location.href="{% url 'article:article_list' %}";
             }else {
                 layer.msg('sorry.');
             }
         },
     });
    }
    </script>
{% endblock %}

templates/article/tag.html
{% extends 'common/background.html' %}
{% block title %}文章标签{% endblock %}
{% load staticfiles %}
{% block body %}
    <div>
    <div class="list-group list1" style="margin-top: 30px">
        <h3 class="text-center">文章标签管理</h3>
        <a>文章标签：{{ article_tags_form.tag }} <input type="button" class="button" value="添加" onclick="add_tag()"></a>
    </div>
    <div style="margin-top: 20px">
        <table class="table table-hover text-center" style="table-layout:fixed">
            <tr>
                <td width="20%">序号</td>
                <td width="40%">标签名称</td>
                <td width="20%">作者</td>
                <td width="20%">操作</td>
            </tr>
            {% for tag in article_tags %}
                <tr id="{{ forloop.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td id="myTable">{{ tag.tag }}</td>
                    <td>{{ tag.author }}</td>
                    <td >
                        <a name="edit" href="javascript:" onclick="edit_tag(this,{{ tag.id }})" style="color: black">
                            <span class="fa fa-pencil"></span>
                        </a>
                        <a name="delete" href="javascript:" onclick="del_tag(this,{{ tag.id }})" style="color: black; margin-left: 20px">
                        <span class="fa fa-trash-o"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    <script type="text/javascript">
    function add_tag() {
        tag = $("#id_tag").val();
        $.ajax({
            url:'{% url "article:article_tag" %}',
            type:'POST',
            data:{"tag":tag},
            success: function (e) {
                if(e=='1'){
                    layer.msg('标签创建成功');
                    window.location.reload();
                }else {
                    layer.msg(e)
                }
            }
        });
    }
    function edit_tag(the,tag_id) {
        var name=$(the).parents("tr").children("td").eq(1).text();
        var index=layer.open({
            type:1,
            area:['400px','200px'],
            title:"编辑栏目",
            content:'<div class="text-center" style="margin-top:2px"><p>请编辑栏目的名称</p>' +
            '<p><input type="text" id="new_name" value="'+name+'"></p></div>',
            btn:['确定','取消'],
            yes:function (index,layro) {
                new_name = $("#new_name").val();
                $.ajax({
                    url:"{% url 'article:edit_tag' %}",
                    type:"POST",
                    data:{"tag_id":tag_id,"tag_name":new_name},
                    success:function (e) {
                        if (e=='1') {
                            parent.location.reload();
                            layer.msg("修改成功");
                        } else {
                            layer.msg("修改失败");
                        }
                    },
                });
            },
        });
    }
    function del_tag(the, tag_id) {
        var article_tag = $(the).parents('tr').children('td').eq(1).text();
        layer.open({
            type:1,
            skin:'layui-layer-rim',
            area:['400px', '200px'],
            title:'删除文章标签',
            content: '<div class="text-center" style="margin-top:20px"><p>是否确定删除文章标签 '+article_tag+' </p></div>',
            btn:['确定', '取消'],
            yes: function () {
                $.ajax({
                    url: '{% url 'article:del_tag' %}',
                    type: 'POST',
                    data: {'tag_id':tag_id},
                    success: function (e) {
                        if(e=='1'){
                            parent.location.reload();
                            layer.msg('删除成功');
                        }else{
                            layer.msg('删除失败');
                        }
                    },
                })
            },
        })
    }
    </script>
    </script>
{% endblock %}